import tarball aegis-2012.11.26-04.025.D505

diff --git a/script/test_funcs.in b/script/test_funcs.in
--- a/script/test_funcs.in
+++ b/script/test_funcs.in
@@ -1,23 +1,22 @@
 #!/bin/sh
 #
-#	aegis - project change supervisor
-#	Copyright (C) 2006 Jerry Pendergraft
-#	Copyright (C) 2007, 2008 Peter Miller
-#	Copyright (C) 2007, 2008 Walter Franzini
+# aegis - project change supervisor
+# Copyright (C) 2006 Jerry Pendergraft
+# Copyright (C) 2007, 2008, 2012 Peter Miller
+# Copyright (C) 2007, 2008 Walter Franzini
 #
-#	This program is free software; you can redistribute it and/or modify
-#	it under the terms of the GNU General Public License as published by
-#	the Free Software Foundation; either version 3 of the License, or
-#	(at your option) any later version.
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 3 of the License, or (at
+# your option) any later version.
 #
-#	This program is distributed in the hope that it will be useful,
-#	but WITHOUT ANY WARRANTY; without even the implied warranty of
-#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#	GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# General Public License for more details.
 #
-#	You should have received a copy of the GNU General Public License
-#	along with this program. If not, see
-#	<http://www.gnu.org/licenses/>.
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
 if [ "$TEST_SUBJECT" = "fill me in" -o "$TEST_SUBJECT" = "" ]
@@ -71,34 +70,35 @@ export AEGIS_DATADIR
 
 pass()
 {
-	set +x
-	echo PASSED
-	cd $here
-	find $work -type d -user $USER -exec chmod u=rwx {} \;
-	rm -rf $work
-	exit 0
+    set +x
+    echo PASSED
+    cd $here
+    find $work -type d -user $USER -exec chmod u=rwx {} \;
+    rm -rf $work
+    exit 0
 }
 fail()
 {
-	set +x
-	cd $here
-	find $work -type d -user $USER -exec chmod u=rwx {} \;
-        rm -rf $work
-	echo "FAILED test of $TEST_SUBJECT ($activity)" 1>&2
-	exit 1
+    set +x
+    cd $here
+    find $work -type d -user $USER -exec chmod u=rwx {} \;
+    rm -rf $work
+    echo "FAILED test of $TEST_SUBJECT ($activity)" 1>&2
+    exit 1
 }
 no_result()
 {
-	set +x
-	cd $here
-	find $work -type d -user $USER -exec chmod u=rwx {} \;
-	rm -rf $work
-	echo "NO RESULT for test of $TEST_SUBJECT ($activity)" 1>&2
-	exit 2
+    set +x
+    cd $here
+    find $work -type d -user $USER -exec chmod u=rwx {} \;
+    rm -rf $work
+    echo "NO RESULT for test of $TEST_SUBJECT ($activity)" 1>&2
+    exit 2
 }
 trap "no_result" 1 2 3 15
 
 activity="create test directory"
+rm -rf $work
 mkdir $work $work/lib
 if test $? -ne 0 ; then no_result; fi
 chmod 777 $work/lib
@@ -129,7 +129,7 @@ unset LC_ALL
 #
 if test "$CXX" != "c++"
 then
-        cat >> $work/c++ << fubar
+    cat >> $work/c++ << fubar
 #!/bin/sh
 exec ${CXX-g++} \$$*
 fubar
@@ -141,4 +141,4 @@ fubar
    export PATH
 fi
 
-# EOF:  etc/test_funcs.sh
+# vim: set ts=8 sw=4 et :
