import tarball aegis-2007.08.13-04.023

diff --git a/etc/template/test b/etc/template/test
--- a/etc/template/test
+++ b/etc/template/test
@@ -1,24 +1,20 @@
 #!/bin/sh
 #
-#	aegis - project change supervisor
-#	Copyright (C) ${date %Y} ${user name};
-#	All rights reserved.
+# aegis - project change supervisor
+# Copyright (C) ${date %Y} ${user name}
 #
-#	This program is free software; you can redistribute it and/or modify
-#	it under the terms of the GNU General Public License as published by
-#	the Free Software Foundation; either version 2 of the License, or
-#	(at your option) any later version.
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or (at
+# your option) any later version.
 #
-#	This program is distributed in the hope that it will be useful,
-#	but WITHOUT ANY WARRANTY; without even the implied warranty of
-#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#	GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# General Public License for more details.
 #
-#	You should have received a copy of the GNU General Public License
-#	along with this program; if not, write to the Free Software
-#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
-#
-# MANIFEST: Test the ??? functionality
+# You should have received a copy of the GNU General Public License along
+# with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
 unset AEGIS_PROJECT
@@ -38,14 +34,14 @@ work=$${AEGIS_TMP:-/tmp}/$$$$
 PAGER=cat
 export PAGER
 AEGIS_FLAGS="delete_file_preference = no_keep; \
-	lock_wait_preference = always; \
-	diff_preference = automatic_merge; \
-	pager_preference = never; \
-	persevere_preference = all; \
-	log_file_preference = never; \
-	default_development_directory = \"$$work\";"
+        lock_wait_preference = always; \
+        diff_preference = automatic_merge; \
+        pager_preference = never; \
+        persevere_preference = all; \
+        log_file_preference = never; \
+        default_development_directory = \"$$work\";"
 export AEGIS_FLAGS
-AEGIS_THROTTLE=2
+AEGIS_THROTTLE=-1
 export AEGIS_THROTTLE
 
 # This tells aeintegratq that it is being used by a test.
@@ -66,7 +62,7 @@ then
     IFS=":$$IFS"
     for tpath2 in $$EXEC_SEARCH_PATH
     do
-	tpath=$${tpath}$${tpath2}/$${parch}bin:
+        tpath=$${tpath}$${tpath2}/$${parch}bin:
     done
     IFS="$$hold"
     PATH=$${tpath}$${PATH}
@@ -87,30 +83,30 @@ export PATH
 
 pass()
 {
-	set +x
-	echo PASSED 1>&2
-	cd $$here
-	find $$work -type d -user $$USER -exec chmod u+w {} \;
-	rm -rf $$work
-	exit 0
+        set +x
+        echo PASSED 1>&2
+        cd $$here
+        find $$work -type d -user $$USER -exec chmod u+w {} \;
+        rm -rf $$work
+        exit 0
 }
 fail()
 {
-	set +x
-	echo "FAILED test of the ??? functionality ($$activity)" 1>&2
-	cd $$here
-	find $$work -type d -user $$USER -exec chmod u+w {} \;
-	rm -rf $$work
-	exit 1
+        set +x
+        echo "FAILED test of the ??? functionality ($$activity)" 1>&2
+        cd $$here
+        find $$work -type d -user $$USER -exec chmod u+w {} \;
+        rm -rf $$work
+        exit 1
 }
 no_result()
 {
-	set +x
-	echo "NO RESULT when testing the ??? functionality ($$activity)" 1>&2
-	cd $$here
-	find $$work -type d -user $$USER -exec chmod u+w {} \;
-	rm -rf $$work
-	exit 2
+        set +x
+        echo "NO RESULT when testing the ??? functionality ($$activity)" 1>&2
+        cd $$here
+        find $$work -type d -user $$USER -exec chmod u+w {} \;
+        rm -rf $$work
+        exit 2
 }
 trap \"no_result\" 1 2 3 15
 
@@ -138,15 +134,15 @@ unset LANGUAGE
 #
 if test "$$CXX" != "c++"
 then
-	cat >> $$work/c++ << fubar
+        cat >> $$work/c++ << fubar
 #!/bin/sh
 exec $${CXX-g++} \$$*
 fubar
-	if test $$? -ne 0 ; then no_result; fi
-	chmod a+rx $$work/c++
-	if test $$? -ne 0 ; then no_result; fi
-	PATH=$${work}:$${PATH}
-	export PATH
+        if test $$? -ne 0 ; then no_result; fi
+        chmod a+rx $$work/c++
+        if test $$? -ne 0 ; then no_result; fi
+        PATH=$${work}:$${PATH}
+        export PATH
 fi
 
 #
